### ISSUE TITLE
Move errors to core 

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#255]
Errors are a part of the interface and should be moved to core

**Comment by joshua-berry-ntnx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Papiea issues needed for inventory-only BMaaS](https://trello.com/c/V6gmTU73/66-address-papiea-issues-needed-for-inventory-only-bmaas)

**Comment by Emulebest** [comment]
This is not a very big one. 1-2 days of work depending on the amount of interconnected code
