### ISSUE TITLE
Don't use the `-` (dash/hyphen) character in property names

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#392]
There are a few places where this is used:

* `x-papiea*` properties in schema definitions
* Differences (`spec-val` and `status-val`)

There are a few reasons to avoid doing this:

1. It's awkward to write and makes code less readable: (`diff['spec-val'].foo` vs `diff.spec_val.foo`)
2. It's harder to use [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) with such properties—you must explicitly map names with `-`s to valid variable names.
3. It doesn't work with JavaScript's `.?` operator for properties which might be undefined.

**Comment by shlomi-nx** [comment]
`x-papiea*` is a must according with https://swagger.io/docs/specification/openapi-extensions/

`spec|status-val` should change yes, but these are not `properties`.

**Comment by joshua-berry-ntnx** [comment]
> `x-papiea*` is a must according with https://swagger.io/docs/specification/openapi-extensions/

Uggghhhh, if we must, we must. I suppose the `x-papiea*` fields are fairly rare anyway.

> `spec|status-val` should change yes, but these are not `properties`.

👍

**Comment by shlomi-nx** [comment]
Closing this. the `-val` removal will be tracked in #421
