### ISSUE TITLE
Create/update entity with a required string property doesn't work if the supplied string value is ""

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#394]
Suppose I have a kind with a string property that is required:

```
{
    type: 'object',
    required: ['foo'],
    properties: {
        foo: {type: 'string'},
    },
}
```

Trying to create an entity of this kind with `foo` explicitly specified as the empty string, like so:

```{spec: {foo: ""}, metadata: {...}}```

...fails with the error: "foo is a required field". I would expect the empty string to be accepted.

**Comment by joshua-berry-ntnx** [comment]
Shlomi told me offline that Papiea uses swagger-model-validator for validation. I had a brief look at their code and I see they have a test case which precisely covers my test above:

https://github.com/swagger-model-validator/swagger-model-validator/blob/master/tests/testStringValidation.js#L118

...and the test case has the wrong behavior. Let me open an upstream bug.

**Comment by shlomiv** [comment]
Please link the upstream bug when you opened it

**Comment by shlomi-nx** [comment]
Please link the upstream bug

**Comment by joshua-berry-ntnx** [comment]
Filed https://github.com/swagger-model-validator/swagger-model-validator/issues/137

**Comment by Emulebest** [comment]
I'll create a regression test on our side as well
