### ISSUE TITLE
python_sdk needs `on_create|delete` as well

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#406]
No need from the `proceed` process for now. Similar to https://github.com/nutanix/papiea/pull/362

**Comment by Emulebest** [comment]
@shlomi-nx haven't thoroughly tested this but I am pretty sure Python SDK already has that https://github.com/nutanix/papiea/blob/85362f7a26b3cb878c9c76fb5be04a33290cdd30/papiea-python-sdk/papiea/python_sdk.py#L535. Regarding #362 these are papiea-engine changes, nothing to be changed on provider's side

**Comment by Emulebest** [comment]
@shlomi-nx did you check this out?

**Comment by shlomi-nx** [comment]
Oh! Must have missed that, thank you! Closing.
