### ISSUE TITLE
Filtering an entity depends on the order of the fields

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#407]
When filtering on one of our kinds, filter with this:
```
{
   "spec": {
     "state": "free",
     "type": {
       "kind": "machine-type",
       "uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
     }
   }
}
```

yield correct results, however, if we transpose any two lines, it fails, such as:
```
{
   "spec": {
     "type": {
       "kind": "machine-type",
       "uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
     },
    "state": "free"
   }
}
```

**Comment by shlomi-nx** [comment]
As far as @joshua-berry-ntnx and I can tell, this was only recently introduced.

**Comment by joshua-berry-ntnx** [comment]
Here is a minimal example of a schema which shows the issue:

```
{
        type: 'object',
        'x-papiea-entity': 'differ',
        properties: {
            a: {type: 'string'},
            b: {
                type: 'object',
                properties: {
                    c: {type: 'string'},
                    d: {type: 'string'},
                },
            },
        }
    }
```

Note that the even simpler example—just `a` and `b` as strings, and swapping the fields, still works. So there is some issue that's specific to objects nested under the top-level spec and status objects.

**Comment by joshua-berry-ntnx** [comment]
(As a side note, I have seen other issues with filtering on nested objects—for example, if you don't specify _all_ of the properties of the nested object you're filtering on, you won't find what you're looking for. Not sure if these two things are related.)

**Comment by shlomi-nx** [comment]
Create an entity of that kind:

```
{"spec": 
  {
   "a":"a",
   "b": {
       "c":"c",
       "d":"d"
    }
  }}
```

Running filter with:
```
{"spec": 
  {
   "a":"a",
   "b": {
       "c":"c",
       "d":"d"
    }
  }}
```

works fine, running it with:

```
{"spec": 
  {
   "a":"a",
   "b": {
       "d":"d",
       "c":"c"
    }
  }}
```

fails (note, I swapped `c` and `d`)
