### ISSUE TITLE
Tidy up SDKs

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#427]
Currently there are unused parameters lurking around (e.g. rbac, Procedural_Execution_Strategy, etc). Lets remove these and clean up. Perhaps take some of the improvements from @joshua-berry-ntnx's sdk wrapper into the mainstream sdk, and reflect some of these in the python SDK.

Another thing is I would like to the repo a bit, we should have 
/ papiea-sdk
  / typescript
    ...
  / python
    ...

**Comment by Emulebest** [comment]
All right, will do
