### ISSUE TITLE
SDK enhancements to filter/list entities 

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#429]
It would be really nice if `EntityCRUD` had a few more features for filtering/listing entities:

* A `list()` function which returns an async iterator over all entities (and incrementally fetches entities using the appropriate offset/limit query parameters)
* Update `filter()` to follow a similar pattern—return an async iterator which incrementally fetches matching entities, as this is what the vast majority of users will want.
* Take a parameter to `list()` and `filter()` which specifies the batch size—so for example, if you call `filter()` intending only to fetch 1 or 2 entities, you can give this hint to `filter()` to avoid fetching too many entities needlessly.

Additionally, for `filter()` it might be nice (but less critical) to have a similar API to what we have now to return (an estimate of) the total number of results without having to actually fetch all the results. Maybe `count()`?

I imagine this will be relevant for both TypeScript and Python SDKs eventually.

**Comment by Emulebest** [comment]
@joshua-berry-ntnx I think it would be beneficial if you could provide a usability example of how you see the workflow of working with this. Meanwhile, I'll provide an implementation of my own and we can then make adjustments
