### ISSUE TITLE
validation should fail on `status-only` fields that are `required`

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#468]
`required` in spec/status land denotes those fields in spec that the user must provide when creating an entity. When a `status-only` field is `required`, the entity cannot be created.

@joshua-berry-ntnx disagrees that `required` must only pertain to `spec` fields, and for a good reason. Having tighter schema on status as well is useful as a contract. However, this requires a more through discussion. 

We could potentially find a middle ground for now by removing required fields from the spec portion when generating the schema specs if the fields are status only.

**Comment by joshua-berry-ntnx** [comment]
Agree with the proposed middle ground.

**Comment by Emulebest** [comment]
@shlomi-nx sorry didn't get what the solution is from the description
'We could potentially find a middle ground for now by removing required fields from the spec portion when generating the schema specs if the fields are status only.'

Could you explain a bit clearer please?

**Comment by shlomi-nx** [comment]
Yes, currently, required status-only fields do not show up in the `Spec` portion of the swagger, but they do appear in the `required` section of the `Spec` portion. They should only appear in the `required` section of the `Status` portion.

**Comment by Emulebest** [comment]
@shlomi-nx if I remember correctly, we don't have different validation schemas for `spec` and `status`. We could introduce different required sections in the format like `spec-required` and `status-required` if that is what you meant

**Comment by shlomi-nx** [comment]
During a call we decided to go with the original idea: required on status only will emit a warning message of being ignored. No invalid swagger will be generated. 

We need to remove status only fields from the list of required fields in the generated Spec portion of each kind's swagger.
