### ISSUE TITLE
spec_version should not be reused for different generations of the same entity

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#471]
Per https://github.com/nutanix/papiea/issues/455#issuecomment-662803382, updates to an entity which have been deleted and subsequently recreated should fail. From the original comment:

> One thing we need to think about: spec_version. We should probably ensure spec_version is somehow unique or different between previous and new versions of a particular entity. Otherwise you could wind up in pathological cases like this:
> 
> 1. Client A fetches info on an entity, which has spec_version 1, then gets delayed, swapped out, decides to take a nap, etc.
> 2. Client B deletes the entity
> 3. Client C creates the entity again, which gets spec_version 1.
> 4. Client A wakes up and tries updating the entity with spec_version 1. The update succeeds, even though the entity has been deleted and recreated.
> 
> So I think we may want to consider persisting the spec_version even after the entity is gone, at least for a reasonable amount of time (and make deletion be a spec_version increment).

**Comment by shlomi-nx** [comment]
(reposting my https://github.com/nutanix/papiea/issues/455#issuecomment-663158290)

That is a fantastic idea. I am not sure about making the deletion a spec_version increment, but when creating a new entity, search the graveyard and create the new entity with max(graveyard(id).map(spec_version))+1

**Comment by joshua-berry-ntnx** [comment]
Yes, I think this achieves the same end goal.

BTW, I see we are not requiring a current `spec_version` on DELETE; we should probably consider this because it affords clients an opportunity to catch update-vs.-delete races. I'm not entirely sold on doing this because it comes at the expense of making DELETE more complex (since clients would have to delete in a GET/DELETE/handle-conflicts loop), but I think it's at least worth considering/discussing further.

**Comment by shlomiv** [comment]
Interesting point.. definitely requires some discussion.. However, lets go ahead with the proposal above for now and discuss this later.

**Comment by joshua-berry-ntnx** [comment]
Yes of course. We can open a separate issue for the DELETE thing if we don't get to it before closing this one out.
