### ISSUE TITLE
Fix up swagger errors

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#478]
Our swagger generator seems to emit errors:

<img width="1440" alt="Screen Shot 2020-07-29 at 8 21 31 AM" src="https://user-images.githubusercontent.com/39283673/88819439-d77e1f80-d174-11ea-998a-ea0b19b00c30.png">

Please make sure that swagger is generated without papiea caused errors. Also add tests for that.

**Comment by Emulebest** [comment]
Could you provide steps to reproduce because I see this:
![image](https://user-images.githubusercontent.com/26462528/89163226-ef431280-d57d-11ea-9a46-2421795a6a57.png)

**Comment by shlomiv** [comment]
Is this your entire screen? You did not see `Invalid` on the bottom right? Lets get on a call.

**Comment by shlomi-nx** [comment]
```
{
    "messages":[
        "attribute paths.'/provider/'(post).responses is missing"
    ],
    "schemaValidationMessages":[
        {
            "level":"warning",
            "domain":"validation",
            "keyword":"format",
            "message":"format attribute \"uri-reference\" not supported",
            "schema":{
                "loadingURI":"#",
                "pointer":"/definitions/License/properties/url"
            }
        },
        {
            "level":"error",
            "domain":"validation",
            "keyword":"required",
            "message":"object has missing required properties ([\"responses\"])",
            "schema":{
                "loadingURI":"#",
                "pointer":"/definitions/Operation"
            },
            "instance":{
                "pointer":"/paths/~1provider~1/post"
            }
        }
    ]
}
```

**Comment by shlomi-nx** [comment]
If you take it to swagger editor you can get much better errors:
```
Errors
Hide
 
Structural error at components.schemas.subnet-Spec.properties.tenant_ref.required
should NOT have duplicate items (items ## 2 and 5 are identical)
i: 5
j: 2
Jump to line 2319
Structural error at components.schemas.subnet-Status.properties.tenant_ref.required
should NOT have duplicate items (items ## 2 and 5 are identical)
i: 5
j: 2
Jump to line 2396
Structural error at components.schemas.subnet.properties.tenant_ref.required
should NOT have duplicate items (items ## 2 and 5 are identical)
i: 5
j: 2
Jump to line 2484
```

**Comment by nitesh-idnani1** [comment]
> If you take it to swagger editor you can get much better errors:
> 
> ```
> Errors
> Hide
>  
> Structural error at components.schemas.subnet-Spec.properties.tenant_ref.required
> should NOT have duplicate items (items ## 2 and 5 are identical)
> i: 5
> j: 2
> Jump to line 2319
> Structural error at components.schemas.subnet-Status.properties.tenant_ref.required
> should NOT have duplicate items (items ## 2 and 5 are identical)
> i: 5
> j: 2
> Jump to line 2396
> Structural error at components.schemas.subnet.properties.tenant_ref.required
> should NOT have duplicate items (items ## 2 and 5 are identical)
> i: 5
> j: 2
> Jump to line 2484
> ```

Can I get the root model/file that's giving this error @shlomi-nx?
I'm checking papiea models and was not able to find error related to the above ones.

**Comment by shlomi-nx** [comment]
Perhaps the specific above ones have changed. Just take a look at any bmaas schema. Let me try to paste it here.
