### ISSUE TITLE
Make a Changelog for Papiea

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#485]
For now let's have it automatically generated out of commits.

**Comment by Emulebest** [comment]
Let's instead pull the changelog from issues but for now keep it simple (name and link)

**Comment by Emulebest** [comment]
Keep in mind that we need optional manual descriptions for the major releases

**Comment by NikitaChernenkoNutanix** [comment]
One of the possible implementations to have a well-structured changelog alongside with proper semantic versioning is to use this approach to name commits:
https://www.conventionalcommits.org/en/v1.0.0/

It will bring us an ability to correctly bump versions on merge to master (as currently, we keep updating patch version which is not according to semantic versioning)

As well as that will help to create a well-structured log out of the commits on merge to master. For example, there is a python lib that works well to fix such structure. https://pypi.org/project/python-changelog/. It expands a file named Changelog.md
that we will be able to correct manually on major releases.

**Comment by NikitaChernenkoNutanix** [comment]
If the structure of conventional commits seems to tight, we can determine our own commit structure and set the rules we want to parse it to changelog. One of the solutions is https://pypi.org/project/gitchangelog/ that works with custom commit structure to create changelog.

However, it might not help us with versioning (there may be a parser of the custom structure for version bumping, needs further investigation).

**Comment by NikitaChernenkoNutanix** [comment]
The last option is to directly print commit messages with the structure we have now in the changelog. it doesn't require a change of the way we write commits but may bring less value to our users.

**Comment by joshua-berry-ntnx** [comment]
Nice, I didn't know about conventional commits. I do think it's going to be a bit hard for us to remember to follow though.

Did you also get a chance to look into generating a ChangeLog from issues/PRs? I don't remember if you were part of the discussion with Shlomi, Igor and I on this topic, but I think issues/PRs are generally going to be a bit higher-level and would make for more useful inputs for a ChangeLog—IMO we can start with something relatively basic like capturing issue/PR summaries and providing links back to each issue/PR, and see how that looks.

**Comment by Emulebest** [comment]
Went through the docs, agree with @joshua-berry-ntnx. Moreover, tight commit structure could be a road block for potential new contributors to papiea, especially if we are going to use something custom

**Comment by NikitaChernenkoNutanix** [comment]
then let's go with PR name and link to it (that basically means commit message title and the link to the PR) for now to keep it simple.

**Comment by Emulebest** [comment]
closed by #500
