### ISSUE TITLE
Papiea endpoints should be HTTPS in production

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#488]

**Comment by shlomi-nx** [comment]
As we discussed on the call:

1. All endpoints (in SDK and Clients) are already configurable and do not restrict https use
2. Papiea engine uses `express` which can be set up to serve https
3. In production - Papiea should be behind an LB/nginx/envoy/k8s etc which will proper SSL termination

I suppose the only thing this ticket should track is exposing some env-vars for docker-compose to enable https serving in express (2). 

### However, this should NOT be the production solution at all. Production solution is (3).

**Comment by shlomi-nx** [comment]
This ask is really an ask of deployment. We should track that in the Customer-1 board.

**Comment by joshua-berry-ntnx** [comment]
Reopened because from discussion with Igor, it seems like putting a reverse proxy in front of Papiea might cause some unwanted issues. So we should have a way to enable HTTPS on the Express server itself in papiea-engine. (And maybe we should make it the default so we are secure-by-default?)
