### ISSUE TITLE
Papiea returns HTTP 500 if provider (or maybe kind) not found

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#502]
If a client tries to make a request against a provider that doesn't exist (or hasn't been registered yet), Papiea returns the following error:

```
{
      code: 500,
      errors: [
        {
          message: 'Provider with prefix bmaas and version 0.0.1 not found'
        }
      ],
      message: 'Provider with prefix bmaas and version 0.0.1 not found',
      type: 'server_error'
    }
```

IMO this should be a 404 (not found) error, or maybe 400 (bad request). We should also check how invalid kinds, procedures, etc. are handled to make sure we return 404 there too.

(I'm not sure whether 404 or 400 would be more appropriate—is there an HTTP status for "This isn't here, AND moreover you shouldn't have asked for it" or is that just 404 with an appropriate error?)

I've worked around this in the BMaaS test scripts for now, so this is lower priority, but might be a good smaller task to take on.

**Comment by Emulebest** [comment]
Yeah, this is an oldie. We talked about this like 1.5 years ago :)

**Comment by nitesh-idnani1** [comment]
Checked the papiea-engine and found out that the get_provider in provider_db_mongo file throws a generic error type. Switched it to EntityNotFoundError and we now get an 404 error code if provider is not registered. Also, I think a lot of the methods throw the generic error, so we may have to revisit the engine and rectify such code.

Note: Tested this using the python sdk, haven't reproduced this on the typescript sdk.
