### ISSUE TITLE
Ability to disable verbose logging

### ISSUE THREAD

**Issue by abhi-nutanix** [nutanix/papiea#513]
Right now Papiea client logs too many internal details that makes debugging for provider code difficult. 
```
bmaas_1   |       chunkedEncoding: false,
bmaas_1   |       destroyed: false,
bmaas_1   |       finished: true,
bmaas_1   |       insecureHTTPParser: undefined,
bmaas_1   |       maxHeaderSize: undefined,
bmaas_1   |       maxHeadersCount: null,
bmaas_1   |       method: 'POST',
bmaas_1   |       outputData: [],
bmaas_1   |       outputSize: 0,
bmaas_1   |       parser: null,
bmaas_1   |       path: '/services/bmaas/0.0.1/machine',
bmaas_1   |       res: IncomingMessage {
bmaas_1   |         [Symbol(kCapture)]: false,
bmaas_1   |         _consuming: false,
bmaas_1   |         _dumped: false,
bmaas_1   |         _events: [Object: null prototype] {
bmaas_1   |           data: [Function: handleStreamData],
bmaas_1   |           end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
bmaas_1   |           error: [Function: handleStreamError]
bmaas_1   |         },
bmaas_1   |         _eventsCount: 3,
bmaas_1   |         _maxListeners: undefined,
bmaas_1   |         _readableState: ReadableState {
bmaas_1   |           [Symbol(kPaused)]: false,
bmaas_1   |           autoDestroy: false,
bmaas_1   |           awaitDrainWriters: null,
bmaas_1   |           buffer: BufferList { head: null, length: 0, tail: null },
bmaas_1   |           closeEmitted: false,
bmaas_1   |           closed: false,
bmaas_1   |           decoder: null,
bmaas_1   |           defaultEncoding: 'utf8',
bmaas_1   |           destroyed: false,
```

Provide ability to disable verbose logging.

**Comment by Emulebest** [comment]
Are the logs from `papiea-client` or `papiea-engine` or any other module?

**Comment by abhi-nutanix** [comment]
This is on BMaaS which is using papiea client.

**Comment by joshua-berry-ntnx** [comment]
This is likely coming from the SDK and maybe the engine as well. I think we have a problem with the SDK in particular where exceptions will log huge amounts of information like axios internals (which I see in the excerpt above) that are irrelevant for actually understanding the problem.

As a first cut, maybe we can start with the exception logs from the SDK and engine, and limit those maybe to the info that is included in the audit log plus any error information (stack trace, message, response code/data, etc.). Then let's see how the log verbosity is.

Second cut would probably be to take a look at cutting down the info in the audit logs themselves, although I think those are just lots of HTTP headers etc. that we may still want to keep for debugging purposes (especially once security comes into the picture).

**Comment by nitesh-idnani1** [comment]
As I see, the major component in case of error logs are the Axios request and response (which again entails the request object) objects. I'm trying to figure out how to redirect/disable them and couldn't find much so let's discuss this.

**Comment by joshua-berry-ntnx** [comment]
After some investigation, this is actually not coming from Papiea itself, but our provider. I still think we can still do some improvement in Papiea for how errors caught by the SDK (and caught in general) are logged. Will post suggestions once I have worked it out in our provider.

**Comment by joshua-berry-ntnx** [comment]
Here's how I changed the logging messages in the provider:

```ts
            try {
                return await fn(await this.wrap(ctx), ...args)
            } catch (e) {
                if (e.config && e.request && e.response) {
                    ctx.get_logger().error(`Unhandled request failure:`, {
                        message: e.message,
                        request: {
                            method: e.request.method,
                            url: e.config.url,
                            headers: e.config.headers,
                            data: json_or_str(e.config.data),
                        },
                        response: {
                            status: e.response.status,
                            statusText: e.response.statusText,
                            headers: e.response.headers,
                            data: json_or_str(e.response.data),
                        },
                        stack: e.stack,
                    });
                } else {
                    ctx.get_logger().error(`Unhandled exception:`, e);
                }
                throw e;
            }
```

@nitesh-idnani1 @Ntnx-Igor-Korotach Can we do something similar here?

**Comment by nitesh-idnani1** [comment]
I'm checking what papiea is giving as output and will reduce it using the above logic. Thanks @joshua-berry-ntnx .
