### ISSUE TITLE
Papiea Clients (Python, Typescript) should contains intent watcher manipulation tools

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#515]
Please provide tools to both client with the following functionalities:
1) get intent watcher by id
2) list intent watchers
3) filter intent watchers
4) wait for status change (wrap into a Promise/asyncio.ensure_future/other ways to make it async)

**Comment by nitesh-idnani1** [comment]
Using the current python sdk test PR to resolve this, since it already has the python sdk testing setup

**Comment by Emulebest** [comment]
> Using the current python sdk test PR to resolve this, since it already has the python sdk testing setup

I'd rather we have a separate PR, since the one with the testing is:
1) Rather big
2) Devoted to Python testing (Typescript not in the scope)
3) Has needed functions as part of testing utils, not modules themself

What you could do is branch off of the testing branch and target PR to be merged to that branch

**Comment by nitesh-idnani1** [comment]
The last functionality i.e. wait_for_status_change has no dependency on the intent watcher, since it polls the entity and not the intent watcher status. Should that be part of the API or a separate module?
