### ISSUE TITLE
Dependant status handler doesn't work properly

### ISSUE THREAD

**Issue by NikitaChernenkoNutanix** [nutanix/papiea#531]
### System Details

- **Papiea Engine version**: nutanix-docker.jfrog.io/papiea:0.7.10_1592
- **Papiea SDK version:** 1.0.90
- **Papiea Client version:** 1.0.90

### Describe the Bug
I have two fields on an entity: `netlinks` and `state`. Both have intent handlers assigned. State handler always waits for netlinks to be resolved prior it starts working. Both fields get updated at the same time (spec is updated) that causes 2 diff, one for `netlinks` and one for `state`. When netlinks intent handler is chosen to be resolved first, the system works as expected. When state intent handler is chosen to be resolved first, it runs over and over and never gets the netlinks intent handler to be resolved (as it never runs in such a case).

to put it generally, if we have a and b intent handler and b depends on a and they get updated at the same time, it doesn't work as expected when b is chosen first and works fine when a is chosen first. This happens because once a handler to be run is chosen it never lets the second one run between its runs.

### Bug information
FIelds schema:
```
        state: {
            type: 'string',
            enum: [
                // Machine is being provisioned
                State.Provisioning,
                // Machine is fully-provisioned and ready for use
                State.Online,
                // Machine has failed or terminated
                State.Terminated,
            ],
            description: 'Machine state',
        },
        netlinks: {
            type: 'array',
            description:
                'A list of network links configured for this instance',
            'x-papiea': 'status-only',
            items: {
                type: 'object',
                required: ['label', 'network_name', 'subnet_name'],
                properties: {
                    label: {
                        // TODO must be unique
                        type: 'string',
                        enum: [
                            // Required to assign AHV ip
                            NetlinkLabel.AHV,
                            // Required to assign CVM ip
                            NetlinkLabel.CVM,
                        ],
                        description:
                            `A user-defined string identifying a particular netlink`,
                    },
                    network_name: {
                        type: 'string',
                        description: 'Name of the network'
                    },
                    subnet_name: {
                        type: 'string',
                        description: 'Name of the subnet'
                    },
                    ip: {
                        type: 'string',
                        description: 'Allocated ip'
                    },
                },
            },
        },
```

intent handler declaration
```
    instance.on('state', ctxbuild.wrap_fn(Instance.on_state));
    instance.on('netlinks.+{label}',
        ctxbuild.wrap_fn(Instance.on_netlink_added));
```
Intent handlers definition (simplified)
```
export async function on_netlink_added(
    ctx: Context, instance: Entity, diff: Difference<Netlink>[]): Promise<void> {
    const subnet_kind = ctx.kind(Subnet.KIND)
    const instance_kind = ctx.kind(KIND)

    ctx.audit("diff", diff)
    for (const {spec: [spec]} of diff) {
        // TODO remove when http://github.com/nutanix/papiea/issues/527 is fixed
        const args: any = {workaround_dummy_string: ""}
        if (spec.ip){
            args.ip = spec.ip
        }
        const {ip} = await subnet_kind.invoke_procedure(
            'alloc_ip', spec.subnet, args);
        const new_netlink = {
            ...spec,
            ip: ip,
        }
        netlinks.push(new_netlink);
        await ctx.update_status(current_instance.metadata, {netlinks});
}
}

export async function go_online(
    ctx: Context, instance: Entity, state: State
): Promise<void> {
    if (!await can_go_online(ctx, instance)) {
        return
    }
}

async function can_go_online(ctx: Context, instance: Entity) {
    if (!deepEqual(instance.status.netlinks, instance.spec.netlinks)){
        ctx.info("The instance can't go online yet, " +
            "its netlinks have not been resolved in inter handler",
            {
                desired: instance.spec.netlinks,
                current: instance.status.netlinks
            })
        return false
    }
    return true
}
```

### Expected/Actual Behavior
We want either to be able to specify the order of intent handlers to be resolved or to make intent handlers run concurrently to each other. with two intent handlers a, b we expect the following timeline of invocation
`a b a b a b` and not `a a a a a a b b b b` or `b b b b b a a a a a`

### Steps to Reproduce

1. Add an entity with 2 fields
2. Add 2 intent handlers for them
3. Make one dependant on another resolution (check that the spec is the same as the state)
4. Observe that when the waiter handler runs first - things never resolve as (the dependant one never runs) and normal behavior when dependant runs first  

### Impact
For now I call the update 2 times in the order I want handlers to resolve, but it seems like a hack

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
@shlomi-nx While modelling the situation as a test I found this pattern.
 
We have a rule that only a single diff could be `Active` at any time. Let's suppose we have:
1) Diff handler `on_x()`
2) Diff handler `on_y()`

Diff handler `on_x()` depends on the execution of `on_y()`, thus requiring `on_y()` to be executed first. We don't specify this anywhere, only depending on the randomness factor.

Diff handler `on_x()` starts executing, finished w/o changing the state and advancing the diff resolution. BUT becomes `Active` and is retried indefinitely. We cannot launch `on_y()` since it will give us 2 `Active` diffs which violates the rule. There are no scenarios to put `Active` diff back to `Pending` as of now so technically this is not achievable.

What is the correct flow in this situation?

**Comment by shlomi-nx** [comment]
a handler should be in `Active` only if it is running, not if it needs to rerun. Why can't an `Active` diff move back to `Pending`? This seems like a design bug that needs to be resolved. The whole idea of diff resolution was that the engine could discover which one is the right one by trying different ones until one completed successfully.
