### ISSUE TITLE
Error messages should be more descriptive

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#534]
There are 2 places that should be fixed:

1) Error when a parameter is not allowed/forgotten to be added to the input value
```
papiea_1   |    { error:
papiea_1   |       { code: 400,
papiea_1   |         errors: [ { message: 'Allowed body params input' } ],
papiea_1   |         message: 'Bad Request',
papiea_1   |         type: 'bad_request_error' } },
```
2) When validation fails because of schema form not being correct
```
papiea_1  |                 Cause: stacktrace - Error: TypeError: expectedType.toLowerCase is not a function
```

**Comment by nitesh-idnani1** [comment]
> toLowerCase

@Emulebest Can you add how you're reproducing the second error, since it is a JavaScript error I need to debug what code/logic is throwing this error?

**Comment by nitesh-idnani1** [comment]
> There are 2 places that should be fixed:
> 
> 1. Error when a parameter is not allowed/forgotten to be added to the input value
> 
> ```
> papiea_1   |    { error:
> papiea_1   |       { code: 400,
> papiea_1   |         errors: [ { message: 'Allowed body params input' } ],
> papiea_1   |         message: 'Bad Request',
> papiea_1   |         type: 'bad_request_error' } },
> ```
> 
> 1. When validation fails because of schema form not being correct
> 
> ```
> papiea_1  |                 Cause: stacktrace - Error: TypeError: expectedType.toLowerCase is not a function
> ```

@Emulebest Can you add how you're reproducing the second error, since it is a JavaScript error I need to debug what code/logic is throwing this error?

**Comment by Emulebest** [comment]
> > There are 2 places that should be fixed:
> > 
> > 1. Error when a parameter is not allowed/forgotten to be added to the input value
> > 
> > ```
> > papiea_1   |    { error:
> > papiea_1   |       { code: 400,
> > papiea_1   |         errors: [ { message: 'Allowed body params input' } ],
> > papiea_1   |         message: 'Bad Request',
> > papiea_1   |         type: 'bad_request_error' } },
> > ```
> > 
> > 
> > 
> > 1. When validation fails because of schema form not being correct
> > 
> > ```
> > papiea_1  |                 Cause: stacktrace - Error: TypeError: expectedType.toLowerCase is not a function
> > ```
> 
> @Emulebest Can you add how you're reproducing the second error, since it is a JavaScript error I need to debug what code/logic is throwing this error?

Sure, let's talk about this one on the call

**Comment by Emulebest** [comment]
Part 2 of the issue depends on https://github.com/swagger-model-validator/swagger-model-validator/pull/144 to be merged
