### ISSUE TITLE
Intent handler still running after deletion of associated entity 

### ISSUE THREAD

**Issue by abhi-nutanix** [nutanix/papiea#537]
Component | Version
-- | --
Engine (docker) | nutanix-docker.jfrog.io/papiea:0.7.20_1657
Client/SDK (typescript) | 0.7.20+1657
Client/SDK (python) | 0.7.20+1657

**Comment by joshua-berry-ntnx** [comment]
@abhi-nutanix Can you please add some more details to the description? What exactly are you seeing? Expected/actual behavior descriptions, logs, etc. would be helpful here.
