### ISSUE TITLE
Intent handlers think that status-only field presence on state is a diff

### ISSUE THREAD

**Issue by NikitaChernenkoNutanix** [nutanix/papiea#540]
### System Details

- **Papiea Engine version**: nutanix-docker.jfrog.io/papiea:0.7.10_1592
- **Papiea SDK version:** 1.0.90
- **Papiea Client version:** 1.0.90

### Describe the Bug
The only difference between spec and state is the presence of a status-only field on the status and the absence of it on spec.
However, the intent handler still tries to resolve it

### Bug information
schema
```
{
   "type":"object",
   "title":"Subnet",
   "x-papiea-entity":"differ",
   "required":[
      "test"
   ],
   "properties":{
      "test":{
         "type":"array",
         "items":{
            "type":"object",
            "properties":{
               "id":{
                  "x-papiea":"status-only",
                  "type":"string"
               },
               "a":{
                  "x-papiea":"status-only",
                  "type":"string"
               },
               "b":{
                  "type":"string"
               }
            }
         }
      }
   }
}
```

intent handler registration:
```
subnet.on('used_ips.{id}', ctxbuild.wrap_fn(Subnet.on_id_updated));
```

intent handler implementation:
```
export async function on_id_updated(
    ctx: Context, subnet: Entity, diff: Difference<Test>[],
): Promise<void> {
    ctx.info("diff", diff);
}
```

diff:

```
'0': {
    key: 'test',
        keys: { id: '1' },
    spec: [
        {
            id: '1',
            b: 'test'
        }
    ],
        status: [
        {
            id: '1',
            a: 'test',
            b: 'test'
        }
    ]
}
```

entity spec
```
      {
            id: '1',
            b: 'test'
       }
```

entity state

```
        {
            id: '1',
            a: 'test',
            b: 'test'
        }
```

### Expected/Actual Behavior
I expect no diff to appear when only a status-only field is a difference

### Steps to Reproduce
0. Create intent handler on an update for an entity,
1. Create an entity schema with a normal field and a status-only optional field
2. Create an entity
3. Update its state and add optional status-only to it
4. Observe a diff in the intent handler

### Impact
Currently, we have to mark the field as a normal field and update spec and status together not to have a diff

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by shlomi-nx** [comment]
Can you generate a minimal schema that exhibits this problem?

**Comment by NikitaChernenkoNutanix** [comment]
> Can you generate a minimal schema that exhibits this problem?
> 
> Also, please post the entity values (spec and status) which generated the diff, as well as the SFS.

Done

**Comment by shlomi-nx** [comment]
> > Can you generate a minimal schema that exhibits this problem?
> > Also, please post the entity values (spec and status) which generated the diff, as well as the SFS.
> 
> Done

Well, that's not really a minimal schema that exhibits the problem.

**Comment by NikitaChernenkoNutanix** [comment]
fixed

**Comment by shlomi-nx** [comment]
Differ code itself (the part in clojure) is not familiar with the schema, thoughts of introducing it gave me nightmares 😆 . @Ntnx-Igor-Korotach, @nitesh-idnani1, Do we have some function available which can strip `status` of all `status-only` fields recursively by inspecting the schema? If we have that, we can simply wrap the `status` input with it before invoking the differ itself.

**Comment by nitesh-idnani1** [comment]
> Differ code itself (the part in clojure) is not familiar with the schema, thoughts of introducing it gave me nightmares 😆 . @Ntnx-Igor-Korotach, @nitesh-idnani1, Do we have some function available which can strip `status` of all `status-only` fields recursively by inspecting the schema? If we have that, we can simply wrap the `status` input with it before invoking the differ itself.

I've a recursive logic which inspects the schema and performs an action if certain conditions are met (in my case replacing null with empty object). We can extend it to re-use the inspect logic and perform actions based on flags passed, to make it more generic. Please refer this [code](https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/provider/provider_api_impl.ts#L138)

**Comment by shlomi-nx** [comment]
> > Differ code itself (the part in clojure) is not familiar with the schema, thoughts of introducing it gave me nightmares 😆 . @Ntnx-Igor-Korotach, @nitesh-idnani1, Do we have some function available which can strip `status` of all `status-only` fields recursively by inspecting the schema? If we have that, we can simply wrap the `status` input with it before invoking the differ itself.
> 
> I've a recursive logic which inspects the schema and performs an action if certain conditions are met (in my case replacing null with empty object). We can extend it to re-use the inspect logic and perform actions based on flags passed, to make it more generic. Please refer this [code](https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/provider/provider_api_impl.ts#L138)

Looks good. In that case, perhaps I can assign this task to you. Essentially, use this logic to strip status-only fields from `status` (we can call it `stripper`), then make sure to `strip` the status value that is being passed to the differ. If you have any questions, let me know!

**Comment by Emulebest** [comment]
> > Differ code itself (the part in clojure) is not familiar with the schema, thoughts of introducing it gave me nightmares 😆 . @Ntnx-Igor-Korotach, @nitesh-idnani1, Do we have some function available which can strip `status` of all `status-only` fields recursively by inspecting the schema? If we have that, we can simply wrap the `status` input with it before invoking the differ itself.
> 
> I've a recursive logic which inspects the schema and performs an action if certain conditions are met (in my case replacing null with empty object). We can extend it to re-use the inspect logic and perform actions based on flags passed, to make it more generic. Please refer this [code](https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/provider/provider_api_impl.ts#L138)

Please take a look at this code https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/api_docs/api_docs_generator.ts#L664. It kind of does what is required right now

**Comment by nitesh-idnani1** [comment]
> > > Differ code itself (the part in clojure) is not familiar with the schema, thoughts of introducing it gave me nightmares 😆 . @Ntnx-Igor-Korotach, @nitesh-idnani1, Do we have some function available which can strip `status` of all `status-only` fields recursively by inspecting the schema? If we have that, we can simply wrap the `status` input with it before invoking the differ itself.
> > 
> > 
> > I've a recursive logic which inspects the schema and performs an action if certain conditions are met (in my case replacing null with empty object). We can extend it to re-use the inspect logic and perform actions based on flags passed, to make it more generic. Please refer this [code](https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/provider/provider_api_impl.ts#L138)
> 
> Please take a look at this code
> 
> https://github.com/nutanix/papiea/blob/54c6e055fbf17915478b35bb87c4f2218a7643e8/papiea-engine/src/api_docs/api_docs_generator.ts#L664
> 
> . It kind of does what is required right now

Thanks @Ntnx-Igor-Korotach, I'll look at the issue today.
