### ISSUE TITLE
TypeScript SDK: Context update_status() and replace_status() methods do the same thing

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#554]
### System Details

- **Papiea Engine version**: 0.8.5_1748
- **Papiea SDK version:** 0.8.5+1748
- **Papiea Client version:** 0.8.5+1748

### Describe the Bug

`replace_status()` does not actually replace the entire status, it merely updates it. For example, if you have a status `{a: 1, b: 2}`, and you call `ctx.replace_status(entity, {a: 3})`, you will get a status of `{a: 3, b: 2}`.

### Bug information

I looked at the code for `update_status()` and `replace_status()` in `typescript_sdk_context_impl.ts` and confirmed that both are exactly the same code.

### Expected/Actual Behavior

I expect `replace_status()` to actually replace the status (including removing changed items).

### Steps to Reproduce

1. Define an entity kind with two integer fields `a` and `b` (at least `b` should not be a required field)
2. Create an entity with status: `{a: 1, b: 2}`
3. In the provider, call `replace_status(entity, {a: 3})`
4. Observe the entity still has a `b` field

### Impact

Status fields are not cleared that should be cleared, leading to problems when there is stale data in an entity.

### Additional Details

An alternate "solution" would be to solve #528 and similar issues, such that `update_status()` can be used to remove/clear individual fields in the status, and then get rid of `replace_status()` entirely—this would also address my issue because then we could just use `update_status()` to clear/remove fields when needed.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by shlomi-nx** [comment]
Depends on #528 

We decided to just fix #528 and remove `replace_status`

**Comment by Emulebest** [comment]
@joshua-berry-ntnx If this one isn't going to be relevant, please close this

**Comment by joshua-berry-ntnx** [comment]
We can use this issue to track the removal of `replace_status` once #528 is done.

**Comment by shlomi-nx** [comment]
@nitesh-idnani1 
Let's start by deprecating this function on both SDKs.

Please ensure that the behavior is correct (add tests), and add some deprecation warning on these functions.
