### ISSUE TITLE
Destructor is not triggered for "spec-only" entity

### ISSUE THREAD

**Issue by yitingwnutanix** [nutanix/papiea#559]
### System Details

- **Papiea Engine version**: 0.8.5_1748
- **Papiea SDK version:** 0.8.5
- **Papiea Client version:** 0.8.5

### Describe the Bug

The Constructor and Destructor are not triggered for "spec-only" entities. They get called for "differ" entities. 

### Expected/Actual Behavior

The destructor should be called on a Delete request. The constructor should be called on a POST request.

### Steps to Reproduce

1. Create a "spec-only" entity with constructor and destructor. 
2. Send Post and Delete request to create and delete that the entity. 
3. Logs in constructor and destructor are not showed up. 

### Additional Details

[logs_on_papiea_when destructor_is_called.txt](https://github.com/nutanix/papiea/files/5645987/logs_on_papiea_when.destructor_is_called.txt)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
@joshua-berry-ntnx @nitesh-idnani1 @yitingwnutanix This is going to be fixed by #505, just wait a few days for it to get merged
