### ISSUE TITLE
When kind.create is called, on_create handler's input is missing the metadata field

### ISSUE THREAD

**Issue by yitingwnutanix** [nutanix/papiea#579]
When I call `kind.create` with the spec, only the spec is passed to the handler I registered in `on_create`. metadata is not passed to the constructor. 

### System Details

- **Papiea Engine version**: 0.9.6
- **Papiea SDK version:** 0.9.6
- **Papiea Client version:** 0.9.6

### Describe the Bug

I had a subnet entity defined with [Schema](https://github.com/nutanix/bmaas/blob/a2c63d92356bb2f5c697aa8c21c85cc0a0609417/src/kinds/subnet.ts#L16) and it's [constructor](https://github.com/nutanix/bmaas/blob/a2c63d92356bb2f5c697aa8c21c85cc0a0609417/src/kinds/subnet.ts#L92): `async function construct(ctx: Context, subnet: Entity): Promise<void>`The constructor is registered as: `subnet.on_create({input_schema: Subnet.SCHEMA},ctxbuild.wrap_fn(Subnet.construct)); `
When I call `subnet_kind.create(spec)`, I print the parameter` subnet: Entity `in the constructor, there are only specs and the log is is in `Entity['spec']` format. Metadata is not passed to the constructor. I can't get the metadata to update the status. 

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by nitesh-idnani1** [comment]
@Ntnx-Igor-Korotach
We need to discuss this.

**Comment by Emulebest** [comment]
There is no metadata at the point of getting to constructor, entity doesn't exist at this point

**Comment by nitesh-idnani1** [comment]
Fixed this by communicating the constructor changes with @yitingwnutanix.
