### ISSUE TITLE
Diff retry's exponential backoff is too aggressive

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#580]
### System Details

- **Papiea Engine version**: 0.8.8
- **Papiea SDK version:** 0.8.8
- **Papiea Client version:** 0.8.8

### Describe the Bug
When retrying to resolve a failed diff, the exponential backoff is way too aggressive, causing us to wait a disproportionate amount of time to recover from some transient failures. 

### Bug information
Looking at the master branch, here's what I see:

```ts
export function calculateBackoff(retries: number, maximumBackoff: number, entropy: number) {
    return Math.min(Math.pow(2, retries) + entropy, maximumBackoff)
}
```

So every retry delay is roughly twice as long as the previous retry up to some maximum (which seems to be hard-coded to 100 seconds). This means you will reach the maximum delay after just 8 retries (and after about the 5th retry (~16 seconds), the delay will start to get annoyingly long).

### Expected Behavior
Ultimately, this should probably be tunable somehow (even as a default), and I know it's already tunable on an intent-handler-specific basis, but we should have some reasonable/forgiving defaults to be friendly to developers and people who are debugging issues.

I think we should try to tune the backoff to not get super aggressive until after perhaps the 10th retry or so. Maybe use an exponent of something like 1.3 instead of 2?

```
>>> ['%.2f' % min(1.3**n, 100) for n in xrange(20)]
['1.00', '1.30', '1.69', '2.20', '2.86', '3.71', '4.83', '6.27', '8.16', '10.60',
 '13.79', '17.92', '23.30', '30.29', '39.37', '51.19', '66.54', '86.50', '100.00', '100.00']
```

### Impact
Some wasted developer time while waiting for Papiea to retry something that was a transient failure in 100 seconds instead of like 10-20 seconds.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
It could be done. Actually if `PAPIEA_DEBUG` is set to true, we already adjust the entropy function so the same could be done for the backoff function
