### ISSUE TITLE
Background/periodic task scheduling for providers

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#582]
### Problem Description

There are some (perhaps many) situations where providers will need to periodically and/or proactively poll external resources to understand the current state of the world. For example, a provider which manages IoT devices may wish to poll each device to determine its health status, and then expose this information through the corresponding entity's `status` fields. Or the provider may need to periodically poll an external list of devices to determine whether any have been added or removed (such that corresponding entities can be created or deleted).

### Expected/Actual Behavior
For now I think it would be sufficient for a provider to be able to register some type of periodic task with the engine. Any such task could be run by the engine using a mechanism similar to what is done with intent handlers—that is, a single instance of a provider is chosen to run the task, and the engine monitors the task and restarts it if the instance running the task has failed. (And of course the task itself can fail, but I don't have a strong opinion on what happens then. I think it's OK not to restart it—it's already periodic anyway—or perhaps have a configurable policy for what to do in that case.)

Later, some form of work partitioning might be nice, e.g. "for all entities of kind X, periodically run task Y", and have the work monitored and appropriately divided between all instances of a provider. But I don't see an immediate need for this (and I don't think we need to go full MapReduce just yet ;) ). Just mentioning it here as something to keep in the back of our minds.

### Impact
In a non-distributed world, this could be handled by the providers themselves—e.g. through the use of interval timers, cron jobs, etc. However, providers are supposed to be stateless and horizontally scalable, and any such background task necessarily involves maintaining some state if it is long-running.

Without this feature, instances of a provider would have to coordinate amongst themselves to ensure work was not being duplicated and sub-tasks were being partitioned appropriately. One workaround might be to abuse an intent handler—for example, create a special entity with a spec/status `token` field. Have each instance try to periodically change the token's spec such that there is a diff whenever the task should be run. Then the token's intent handler would be run in a single instance chosen by the engine. The intent handler could run the task and when the task is complete, set the `status.token = spec.token`. (Of course, this assumes it's possible for a provider to proactively make calls back to the engine, which I think is possible but haven't looked into.)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
@shlomi-nx @joshua-berry-ntnx Should we start working towards this with Shlomi's implementation idea?

**Comment by joshua-berry-ntnx** [comment]
@Emulebest Sounds good to me.
