### ISSUE TITLE
Sdk throws error if on_create handler is missing for the kind

### ISSUE THREAD

**Issue by nitesh-idnani1** [nutanix/papiea#585]
### System Details
- Papiea Engine version: 0.9.6
- Papiea SDK version: 0.9.6
- Papiea Client version: 0.9.6

### Describe the Bug
When the kind is registered without an on_create handler, the papiea sdk throws a validation error.

### Expected/Actual Behavior
Expected the kind to be registered without the on_create handler and use the default copy logic for entity construction. Got a validation error from the papiea sdk i.e.
`
papiea-engine    | error         2021-01-05T19:23:58.274Z Error msg: Validation failed.. Details: ;
papiea-engine    |                 Cause: message - Error: Unable to validate an undefined value of property: rootModel
`

### Steps to Reproduce
1. Create a provider
2. Define a new kind without on_create handler
3. Call sdk.register to register the new kind
4. Send a post request to create an entity for the above kind

### Impact
Need to fix this since the workaround for the error is to define an empty on_create handler which is not an ideal scenario for the applications using papiea.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by nitesh-idnani1** [comment]
@yitingwnutanix Keep a track of this issue for any relevant changes.

**Comment by yitingwnutanix** [comment]
@nitesh-idnani1 can you also check on_delete? on_delete also has similar issue.
