### ISSUE TITLE
Allow status-only properties in the "required" list of entity schema. 

### ISSUE THREAD

**Issue by yitingwnutanix** [nutanix/papiea#596]
"Required field" means that these field must be set for the entity. It can be both a "status-only" and a normal property. 
We should allow status-only properties in the entity's required list. 
When validating the spec, https://github.com/nutanix/papiea/blob/e531a23927b9e66d4b7d93f05a824d9774332e57/papiea-engine/src/validator/index.ts#L95-L101 We should remove the status-only property from both schema and the required-list. 

```
    public validate_spec(spec: Spec, kind: Kind, allowExtraProps: boolean) {
        const schemas: any = Object.assign({}, kind.kind_structure);
        // remove any status-only field from the schema to pass to validator
        this.remove_schema_fields(schemas, "status-only")
        this.validate(spec, Object.values(kind.kind_structure)[0], schemas,
            allowExtraProps, Object.keys(kind.kind_structure)[0]);
    }

```
### System Details

- **Papiea Engine version**: 0.9.11_1862
- **Papiea SDK version:** 0.9.11_1862
- **Papiea Client version:** 0.9.11_1862

### Describe the Bug

I defined an entity with required list: ["A", "B", "C"]. "B" and "C" are status-only properties. In my constructor, the return value are as follows:
```
{
     metadata: Metadata, 
     status: {A: a, B:b, C:c},
     spec: {A:a}
}
```
I got error from papiea as follows:
```
papiea_1  |    { error:
papiea_1  |       { code: 400,
papiea_1  |         errors:
papiea_1  |          [ { message: 'B is a required field' },
papiea_1  |            { message: 'C is a required field' }, ],
papiea_1  |         message: 'Validation failed.',
papiea_1  |         type: 'validation_error' } },

```
Papiea should ignore these status-only properties that appear in the required list. 

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by yitingwnutanix** [comment]
@joshua-berry-ntnx @shlomi-nx Please check.

**Comment by nitesh-idnani1** [comment]
Also, we need to remove the validation check for the required status-only fields, if we're doing the above changes.
https://github.com/nutanix/papiea/blob/e531a23927b9e66d4b7d93f05a824d9774332e57/papiea-engine/src/validator/index.ts#L185

**Comment by shlomi-nx** [comment]
I am a little confused by this issue. Papiea should have rejected the `required` mark on the `status-only` field. Why was @yitingwnutanix able to mark that field as required? This seems like the bug here.

If we want to re-enable mandatory status-only fields, that should be a different ask.

**Comment by yitingwnutanix** [comment]
I noted the wrong papiea version here. I was using papiea v0.9.6. 
This should be an enhancement for papiea. It's not an issue.

**Comment by yitingwnutanix** [comment]
Card added for this issue: https://github.com/nutanix/papiea/projects/2#card-53390140

**Comment by joshua-berry-ntnx** [comment]
Reopening per discussion in https://github.com/nutanix/bmaas/pull/122#discussion_r564767884

**Comment by joshua-berry-ntnx** [comment]
Moving @shlomi-nx's comment from the board into this issue. Shlomi said:
> This is a false assumption. You can have a nullable required field, which would mean that you still need to use `status.field!` - As I said, this is a false promise. There may still be some merit to it, but it has to be carefully analyzed.

**Comment by joshua-berry-ntnx** [comment]
To summarize some further discussion from Slack, the key question that having `required` status-only fields answers for us is: can we assume a field always has a non-null (or non-undefined) value? If not, we must resort to explicit null/undefined checks, the `!` operator, and similar things because the TypeScript compiler cannot determine whether a field is guaranteed to be valid or not.

Also, this should probably be a separate issue (if it is an issue at all), but if Papiea supports nullable fields at all in `status`, we have an issue with `update_status`, because `update_status({field: null})` means that `field` should be removed, not set to `null`.

**Comment by joshua-berry-ntnx** [comment]
Opened #609 for the required/status-only portion of this. Still need to open another ticket for the `nullable` issue described above.

**Comment by joshua-berry-ntnx** [comment]
Opened #611 for the `nullable` issue, so I think we've fully split this one apart and can close it.
