### ISSUE TITLE
Errors often lack useful context

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#600]
Some errors conveys no context, look at the following example:

```
papiea_1   | Error msg: Validation failed.. Details: ;
papiea_1   |   Cause: message - Error: hardware_id of type 'status-only' is set to be required. Required fields cannot be 'status-only'
```

When looking at the papiea log, how can we tell which provider, kind, version this error is related to? What if some kinds have more than a single `hardware_id` (perhaps show path from spec)? 

We should make sure we report useful context to the users, to help them identify where the problems are coming from.

This is just one example I found, but we should try and find more locations where we give errors without much context.

**Comment by Emulebest** [comment]
@nitesh-idnani1 mind if I'll be taking this from you while we are discussing my other issues?
