### ISSUE TITLE
Python SDK - constructors have heavy ceremony 

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#604]
When declaring a custom constructor in python, we have to use large syntax:
```
ConstructorProcedureDescription(input_schema={actual_schema})
```
Where the user really only cares about `actual_schema`. I know this was made for type-safety, but the check should be pushed down into the sdk. The user should be able to just specify the map.

**Comment by nitesh-idnani1** [comment]
I feel this is difficult to avoid for two reasons
- on_create description expects two parameters i.e. the input schema and the error schema, hence we need that distinction here.
- As for the structure ConstructorProcedureDescription we can avoid that, but we'd still have to use an AttributeDict type since the python sdk uses the variable as dot notation. So, it would be the same thing essentially even if we eliminate that type structure.

**Comment by shlomiv** [comment]
Can you post some links to code here?

**Comment by nitesh-idnani1** [comment]
Yeah, as mentioned in the code here
https://github.com/nutanix/papiea/blob/385004c0dde8712531d736694b9fc05ba4124e48/papiea-sdk/python/e2e_tests/provider_setup.py#L78

on_create expects input_schema and error_schema (which is optional), and if we remove the type structure we will still have to use AttributeDict here like this

**Comment by shlomiv** [comment]
Wait with closing this. Lets get @Ntnx-Igor-Korotach's input on this.

**Comment by shlomi-nx** [comment]
I meant links into the SDK showing what you meant. I dont know when error_schema you refer to, and not sure there aren't ways around this needless ceremony.

**Comment by nitesh-idnani1** [comment]
> Wait with closing this. Lets get @Ntnx-Igor-Korotach's input on this.

Ohh, I closed by mistake. Sorry about that

**Comment by nitesh-idnani1** [comment]
> I meant links into the SDK showing what you meant. I dont know when error_schema you refer to, and not sure there aren't ways around this needless ceremony.

Python SDK: https://github.com/nutanix/papiea/blob/385004c0dde8712531d736694b9fc05ba4124e48/papiea-sdk/python/papiea/core.py#L245
Typescript SDK: https://github.com/nutanix/papiea/blob/385004c0dde8712531d736694b9fc05ba4124e48/papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts#L575

**Comment by Emulebest** [comment]
TypedDict is nothing different from regular dict asides from the type hints. My suggestion would be to see if the first parameter of the on_create function:
1) is a dict
2) doesn't have an input_schema param
which leads to the conclusion that a dict is an input_schema in of itself

**Comment by Emulebest** [comment]
@shlomi-nx in Python SDK you could use:
```            bucket.on_create({
                "input_schema": {
                "Bucket": {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "owner": {
                            "type": "string"
                        },
                        "objects": {
                            "type": "array"
                        }
                    }
                }
            }
            }, procedure_handlers.bucket_create_handler)
```

I wouldn't want to remove/add variance to `input_schema` as a parameter because it will break the contract of 

```
{input_schema: any, error_schemas?: ErrorSchemas}
```

**Comment by shlomi-nx** [comment]
@Emulebest, do you mean we could use the above example right now without any changes? In that case it may be sufficient.

**Comment by Emulebest** [comment]
@shlomi-nx Yes, you could. Please reopen the issue if you need anything else on this
