### ISSUE TITLE
Papiea 0.9.14 has dependency problems

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#610]
### System Details

- **Papiea Engine version**: 0.9.14
- **Papiea SDK version:** 0.9.14
- **Papiea Client version:** 0.9.14

### Describe the Bug
I tried updating Papiea to 0.9.14 and doing a completely fresh build (removing my `node_modules`, etc.), and it seems the papiea-backend-utils package is missing from the installed dependencies. I'm using a recent npm 7.5.1 / node 15.8.0.

### Bug information
The build fails with an error inside `papiea-client`:

```
node_modules/papiea-client/src/entity_client.ts:23:40 - error TS2307: Cannot find module 'papiea-backend-utils' or its corresponding type declarations.

23 import {getTracer, spanOperation} from "papiea-backend-utils"
```

If I look in my `package-lock.json` file, I see entries for `papiea-backend-utils`. Some of them resolve to the right version and some of them resolve to a `file:...` path which does not exist. However, there is no `papiea-backend-utils` directory in my `node_modules`.

### Expected/Actual Behavior
I expected `papiea-backend-utils` to be installed correctly and for the project to build.

### Steps to Reproduce
1. Check out [redacted].
2. Run `make up` in the root of [redacted]'s source tree
3. Run `make build` in [redacted]'s source tree
4. Note that the build fails with the aforementioned error.

### Impact
Cannot build [redacted] at all with an up-to-date Papiea.

### Additional Details
It seems the dependency of `papiea-client` on `papiea-backend-utils` is new, and perhaps unintentional? I'm not sure why this dependency was added, but it seems to be broken. Did the relevant publishing script get updated when the dependency was added?

`git blame` says @Ntnx-Igor-Korotach added this dependency so assigning to him. :)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by shlomi-nx** [comment]
Added the dependency in this commit 1b0e25d5122f82547390882ebc775e98db14ea06

**Comment by shlomi-nx** [comment]
This problem was introduced by the following PR #584. The dependency was added to the client, but skipped from the awesome publish script.

**Comment by Emulebest** [comment]
@joshua-berry-ntnx could this one be closed?

**Comment by joshua-berry-ntnx** [comment]
Yes, this seems to be fixed. Thanks!
