### ISSUE TITLE
logging_verbosity and tracing_config config entities cannot be set thru env variables and have inadequate validation

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#627]
### System Details

- **Papiea Engine version**: master e70375cf (0.9.24)
- **Papiea SDK version:** 0.9.24
- **Papiea Client version:** 0.9.24

### Describe the Bug

There are two very closely related problems:
- It is impossible to set the `logging_verbosity` or `tracing_config` parameters through the environment
- Neither of these options appear to have adequate validation, so setting either of them to an invalid value causes all kinds of weird behavior

### Bug information

From looking at `papiea-engine/utils/arg_parser.ts`, I see that:

```ts
const id: (val: any) => any = (val: any) => JSON.parse(JSON.stringify(val))

const TRANSFORM_FN_MAP: ... = {
...
    logging_verbosity: id,
    tracing_config: id
}
```

But this is clearly wrong as a matter of type safety—these are typed/complex JS values, not strings, yet `JSON.parse` returns a string. I don't think `id` is needed and they should actually just be `JSON.parse`d.

However, this also raises the matter of validation, as setting either of these variables via the environment results in them being set to strings. I tried hacking in JSON.parse in place of `id` as described above, but accidentally set the wrong value for logging_verbosity, and then instead of actual audit logs I got a lot of:

```
error    2021-02-12T01:11:12.638Z TypeError: Cannot read property 'includes' of undefined
    at AuditLogger.log (/code/papiea-engine/build/audit_logging.js:42:31)
        -> /code/papiea-engine/src/audit_logging.ts:64:31
    at ServerResponse.<anonymous> (/code/papiea-engine/build/audit_logging.js:24:22)
        -> /code/papiea-engine/src/audit_logging.ts:45:22
    at ServerResponse.emit (events.js:326:22)
    at onFinish (_http_outgoing.js:735:10)
    at onCorkedFinish (_stream_writable.js:673:5)
    at afterWrite (_stream_writable.js:490:5)
    at afterWriteTick (_stream_writable.js:477:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Expected/Actual Behavior

- Config inputs should be validated, and if the config is invalid, papiea-engine should refuse to start with an appropriate error
- Parse complex config values that come in through the environment properly

### Impact
Unable to change any Papiea logging settings, since the environment variables cannot be set correctly. (We cannot use the config file because Papiea is currently being configured thru a docker-compose file.)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
@joshua-berry-ntnx I will take a look and try to fix this, though I don't think setting complex values through env variables is a good idea anyways. Is there any particular reason to not use https://github.com/nutanix/papiea/blob/master/papiea-engine/papiea-config.yaml?

**Comment by joshua-berry-ntnx** [comment]
> @joshua-berry-ntnx Is there any particular reason to not use https://github.com/nutanix/papiea/blob/master/papiea-engine/papiea-config.yaml by providing it through docker-compose volume sharing?

Yes—it's messier and harder to manage. Currently we do all our configuration through the single `docker-compose.yaml` file itself. Breaking out a config file for Papiea would mean we no longer have all our configuration in one place and it's harder for new developers to know where to look to find what you need. Volume sharing is not great because we are tying the source tree to the deployed container (so updating or moving a source tree becomes a dangerous activity)—this opens the door for weird mishaps like accidentally removing/editing the config of a running container, etc. And this will get even worse for us if (as seems likely due to reasons outside our control) we will need two different instances of Papiea at different versions.
