### ISSUE TITLE
Custom constructors: Validation errors are unclear [was: Mismatch between generated swagger and actual constructor arguments]

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#628]
### System Details

- **Papiea Engine version**: 0.9.24
- **Papiea SDK version:** 0.9.24
- **Papiea Client version:** 0.9.24

### Describe the Bug

If I define a custom constructor with some arbitrary input parameters `{a, b}`, the generated swagger in the UI says I should be able to call the constructor with `a` and `b` parameters at the top level. Yet doing so leads to model validation errors.

It turns out that wrapping `a` and `b` inside a spec (like `{spec: {a: ..., b: ...}}` is required to call the constructor successfully, even though the swagger says this should not be required.

This extra `spec` field is also passed to the constructor function in the provider.

### Expected/Actual Behavior

I expect the swagger to agree with the actual behavior of the constructor—either everything should be wrapped in `spec`, or it shouldn't.

I'm not sure that wrapping everything in `spec` is desirable, since it's quite confusing to place parameters in `spec` which will eventually end up in an entity's `status` when the entity is actually created. Also, given that the constructor parameters might differ quite dramatically from the entity's actual `spec`, it seems misleading to present them as `spec` when they're really just arguments.

Either way, though, the swagger should be consistent with what Papiea actually accepts.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by Emulebest** [comment]
@joshua-berry-ntnx let's speak on the matters on the call. Wrapping the input with spec like ` {spec: {a: ..., b: ...}}` is not how the constructors requires it. `spec` wrapper is completely optional

**Comment by joshua-berry-ntnx** [comment]
I think this might actually be two separate issues.

Unbenkownst to me when I filed this bug, we were setting `'x-papiea': 'status-only'` in the schema for certain fields in our custom constructor. (This obviously doesn't make sense and is a bug on our side, but bear with me for a moment.) Papiea accepted this schema without comment (which it shouldn't have), yet calling the constructor and passing an argument for such a field results in validation errors like: `"Target property 'foo' is not in the model"`

To try to understand why this was happening (and before I realized we were marking these field as status-only), I hypothesized that perhaps `spec` was required to wrap the constructor arguments. So I added it the extra `spec` wrapper, validation no longer failed, and I could see parameters like `foo` appear inside the constructor function as `args.spec.foo`. This is what made me think that Papiea was expecting to see `{spec: {arguments...}}` rather than just `{arguments...}`.

But I'm now thinking there are two bugs:
1. `x-papiea: status-only` should be rejected when it appears in a procedure schema. (Right now it seems we are just pretending those fields don't exist and accepting the schema, at least for custom constructors.)
2. Somehow built-in fields like `metadata`, `spec` and `status` are implicitly part of the constructor schema when they should not be.

(1) I've been able to validate via experimentation—removing `x-papiea: status-only` from a field makes the validation error for that field go away. (2) probably needs a bit more investigation.

**Comment by joshua-berry-ntnx** [comment]
@nitesh-idnani1 and I sat and looked at this some more, and we determined the problem wasn't at all where I thought it was—it was the provider's constructor which was returning a bad entity that did not pass validation, and THOSE validation errors are what I was seeing originally. But the way the errors were reported was very misleading, because they were indistinguishable from a client passing bad data to the constructor.

In `constructor_entity_creation_strategy.ts`, we need to make sure that any errors which escape actually specify whether the constructor argument validation failed, or the entity returned was invalid. Constructor arguments should fail with a 400 error (as they do currently), but entity creation should fail with 500 Internal Server Error (instead of 400 Bad Request) and an appropriate descriptive message indicating the entity returned by the constructor was invalid.

**Comment by nitesh-idnani1** [comment]
I'll try to add some fixes in the improve logging PR. Kindly check and let me know if we need more context/info.

**Comment by Emulebest** [comment]
@nitesh-idnani1 @joshua-berry-ntnx Can you confirm that #623 closes this and we don't need other tests/checks/etc?

**Comment by nitesh-idnani1** [comment]
I'll add a couple of tests to verify the errors are indeed different for "constructor input" v/s "constructor returned entity" validation.
Let me know if we need anything else.

**Comment by shlomi-nx** [comment]
Regarding using wrong flags on swagger definitions, such as `'x-papiea': 'status-only'` on input parameters, we have 2 options:
1. Simply reject any wrong inputs
2. Make a loud warning but ignore the flags

Perhaps we could think of some form of `pedantic` parameter, which can toggle between the two, so during dev time we would not have this on and papiea would ignore some recoverable problems, but during testing and production have it on so that papiea would not accept invalid configurations.
