### ISSUE TITLE
Stop depending on NODE_ENV for formatting logs

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#640]
Currently the log-formatting logic in _papiea-backend-utils_ checks NODE_ENV to tell if we should emit pretty-printed or condensed logs. Instead of checking NODE_ENV, we should add another parameter to the existing logging configuration (which comes through env variables or config files) as to whether we want condensed or pretty-printed output.

As an alternative, we can simply remove the pretty-printed output and ensure that all logs are always emitted as properly-formatted JSON objects. Then it's pretty easy to pretty-print captured logs using something like `jq`.

**Comment by nitesh-idnani1** [comment]
We already had support for setting logging format in the "LoggerOptions" structure (added reference below). So, I just added support to set the logging format through config variable in the linked PR. Let me know if we need to change anything else.
https://github.com/nutanix/papiea/blob/7e8b9916fadc35d81623e79e1c34f37df2966eb2/papiea-backend-utils/src/logging.ts#L173
