### ISSUE TITLE
Audit Papiea for improper error handling

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#658]
There are a few places I've run across in Papiea where we have exception handling that looks something like this:

```ts
try {
    // do something
    return true; // success
} catch (e) {
    return false; // failed
}
```

Nitesh and I ran across a similar example in `diff_resolver.ts` earlier today:

```ts
        try {
            const updated_watchlist = await this.watchlistDb.get_watchlist()
            this.watchlist.update(updated_watchlist)
        } catch (e) {
            return
        }
```

We should never, ever write code that looks like this, because unexpected/unanticipated errors will get swallowed and nobody will be able to debug what's going on.

All our catch blocks should look something like:

```ts
try {
    ...
} catch (e) {
    // First, never assume ANYTHING about `e`.
    // It's perfectly valid to `throw undefined`!

    // For errors that get swallowed/handled specially, we must look
    // for some specific error:
    if (e instanceof ...) { ... }
    if (e?.response?.status == 400) { /* do whatever */ }

    // After checking for specific errors, there are two acceptable
    // ways to end a catch block:

    // Option 1: Re-throw it:
    throw e;

    // Option 2 (in rare cases only): Swallow and log it:
    if (typeof e === 'object') {
        console.log(e.toString());
        console.log(e.stack); // Always log stack if possible
    } else {
        console.log(e.toString());
    }
}
```

We need to audit the codebase, find places where we are swallowing errors or otherwise catching things in a way that doesn't follow the above pattern, and fix them.

**Comment by Emulebest** [comment]
While I agree with the idea, I don't think that approach above will help too much and will certainly bloat the codebase. Why so? Firstly, `instanceof` is not going to help much since you would need to manually set the prototype, which is not done by majority library writers. Secondly, `typeof e === 'object'` isn't of help as well because you can do `throw "I am a dumb JS string error"`. We won't be able to escape swallowed errors entirely (IMO we won't be able to even reduce the rate of those), thus my general advice is to accept that in some cases JS is not very good and process those cases individually. Maybe we should add `instanceof` check where it is somewhat easy to pin point error types but not the above to all suspicious error handling parts (which is all of JS TBH).

This is inherently a Javascript design flaw to not have:
a) adequate type system
b) catch blocks restricted to instance of errors
c) algebraic effects (or at least ADTs)

**Comment by nitesh-idnani1** [comment]
Fixed by error details swallowing PR (#636) commit https://github.com/nutanix/papiea/pull/636/commits/ae54fc295860bf74275b4e769e864cd430db63d8

**Comment by joshua-berry-ntnx** [comment]
Hi @nitesh-idnani1, I think this is issue might be slightly different from your PR, although they are related. For this issue, we should be looking not specifically at logs, but at any place where we do exception handling like what's described above. Were you able to address things like `catch (e) { return; }` in your PR as well?

**Comment by nitesh-idnani1** [comment]
> Hi @nitesh-idnani1, I think this is issue might be slightly different from your PR, although they are related. For this issue, we should be looking not specifically at logs, but at any place where we do exception handling like what's described above. Were you able to address things like `catch (e) { return; }` in your PR as well?

Yes, I based those changes on all instances where I found catch block with swallowed error information

**Comment by joshua-berry-ntnx** [comment]
> While I agree with the idea, I don't think that approach above will help too much and will certainly bloat the codebase. Why so? Firstly, `instanceof` is not going to help much since you would need to manually set the prototype, which is not done by majority library writers. Secondly, `typeof e === 'object'` isn't of help as well because you can do `throw "I am a dumb JS string error"`.

The use of `instanceof` was merely an example of how to look for and specially handle a *specific* type of error. You might use instanceof, or some other method (like checking for certain fields) depending on the error you want to handle specially.  The point here is, for any case where you need some special handling (for example, handling a "not found" error, or an entity update conflict, or similar), you should (carefully) check for that *specific* error, and not assume that you otherwise know anything about what's being thrown.

> We won't be able to escape swallowed errors entirely (IMO we won't be able to even reduce the rate of those), thus my general advice is to accept that in some cases JS is not very good and process those cases individually. Maybe we should add `instanceof` check where it is somewhat easy to pin point error types but not the above to all suspicious error handling parts (which is all of JS TBH).

I don't agree—indeed, the example above shows exactly this, and will handle everything from `throw undefined` to `throw new Error()` to `throw "string"` or even `throw () => {/* function */}`. Is there some bug you can point to?

**Comment by joshua-berry-ntnx** [comment]
@nitesh-idnani1 This one's already in progress right? Can you update the status? Thanks!
