### ISSUE TITLE
Papiea sometimes does not pass up-to-date/complete entity info to procedures or intent handlers

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#675]
### System Details

- **Papiea Engine version**: 0.9.51
- **Papiea SDK version:** 0.9.51
- **Papiea Client version:** 0.9.51

### Describe the Bug

Sometimes it seems Papiea isn't passing fully-complete entity info to procedures, and we have to do an explicit `get()` to retrieve the full entity. For example, properties which I know are set on the entity (and which are not actively being worked on) may be missing entirely.

Most recently I've seen this happen with destructor procedures, but I think I've also seen it happen in intent handlers. Can we make sure we are passing a complete, up-to-date view of the entire entity?

### Bug information
Need to investigate further; filing as a placeholder for now. (And also filing in case someone already knows why this is happening and can provide an easy explanation/fix.)

### Expected/Actual Behavior
Every time a procedure or intent handler is invoked, I expect to receive a complete view of the entity with all the properties present (and with their most recent values at the time of invocation).

### Steps to Reproduce
I need to dig more to find out precisely when/how this happens.

### Impact
Procedures sometimes fail with errors due to the missing properties.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by nitesh-idnani1** [comment]
There are two places where we pass the entity info

1) Destructors
In case of destructors, we fetch the metadata from the spec database and pass it to the handler without any parsing/modification. We can also include the entity spec and status if it's required.

2) on change Intent Handlers
For on change intent handlers, we fetch metadata, spec and status from the database and pass it to the intent handler. I think we might be modifying the spec or status in the differ's sanitizer functions. I'll check and fix that.

For all other user-specified procedures, we just pass the user input to the handler.
