### ISSUE TITLE
Intent handler not called for subnet entity even though there is a diff

### ISSUE THREAD

**Issue by manojsudheendra** [nutanix/papiea#702]
### System Details

- **Papiea Engine version**: 0.9.60
- **Papiea SDK version:** 0.9.60
- **Papiea Client version:** 0.9.60

### Describe the Bug

The subnet entity's diff is never resolved because the intent handler: on_removed_ip never gets called. The subnet entity in question's log from the GET request is posted below. The issue is intermittent and seems specific to this entity since I see the same intent handler getting called for other subnet entities in question. 

### Bug information

{
  "request_ip": "::ffff:172.18.0.4",
  "method": "GET",
  "url": "/services/bmaas/0.0.1/subnet/c533dd8d-a4cd-4784-8f7c-d29f1c294c37",
  "status_code": 200,
  "trace_id": "4fc90bcb4ca775a7",
  "headers": {
    "accept": "application/json, text/plain, */*",
    "authorization": "Bearer bmaas_kool",
    "papiea-version": "0.9.60",
    "uber-trace-id": "4fc90bcb4ca775a7:eca81bee07134532:87b623a107cebd31:1",
    "user-agent": "axios/0.18.1",
    "host": "papiea:3000",
    "connection": "close"
  },
  "request_body": {},
  "response_body": {
    "metadata": {
      "kind": "subnet",
      "provider_prefix": "bmaas",
      "provider_version": "0.0.1",
      "spec_version": 3,
      "uuid": "c533dd8d-a4cd-4784-8f7c-d29f1c294c37",
      "created_at": "2021-05-11T23:08:31.185Z",
      "extension": {
        "owner": "me"
      },
      "status_hash": "fad02aa3ed0ebfe5dd505a439d5b8a9b848c40ec"
    },
    "spec": {
      "provider_ref": {
        "tenant_id": "41706572-7475-7265-2053-6369656e6365",
        "account_id": "5c72afeb-215b-4ac9-882c-6d63077f4728",
        "resource_group": "TestingCenterNutanixStaging",
        "network": "TestChamber01MgmtNutanixStaging",
        "name": "TestChamber01MgmtSubnetNutanixStaging"
      },
      "tenant_ref": {
        "uuid": "f27e11c5-b707-41e0-85fd-5d8bdd31b333",
        "kind": "tenant"
      },
      "used_ips": []
    },
    "status": {
      "provider_ref": {
        "tenant_id": "41706572-7475-7265-2053-6369656e6365",
        "account_id": "5c72afeb-215b-4ac9-882c-6d63077f4728",
        "resource_group": "TestingCenterNutanixStaging",
        "network": "TestChamber01MgmtNutanixStaging",
        "name": "TestChamber01MgmtSubnetNutanixStaging"
      },
      "tenant_ref": {
        "uuid": "f27e11c5-b707-41e0-85fd-5d8bdd31b333",
        "kind": "tenant"
      },
      "cidr": "10.76.0.0/16",
      "used_ips": [
        {
          "ip": "10.76.0.11",
          "owner": {
            "uuid": "4f21363e-15be-4d30-998f-c76eaf425ce7",
            "kind": "machine"
          },
          "provider_ref": {
            "tenant_id": "41706572-7475-7265-2053-6369656e6365",
            "account_id": "5c72afeb-215b-4ac9-882c-6d63077f4728",
            "resource_group": "TestingCenterNutanixStaging",
            "name": "kenny"
          },
          "interface_ref": {
            "tenant_id": "41706572-7475-7265-2053-6369656e6365",
            "account_id": "5c72afeb-215b-4ac9-882c-6d63077f4728",
            "resource_group": "TestingCenterNutanixStaging",
            "name": "kenny-10-76-0-11"
          }
        }
      ],
      "ip_pool": {
        "start": "10.76.0.10",
        "end": "10.76.255.250"
      },
      "netmask": "255.255.0.0",
      "gateway": "10.76.0.1",
      "debug": {
        "running": "on_ip_added_inner"
      }
    }
  },
  "user": {
    "owner": "admin.bmaas@nutanix.com",
    "tenant-email": "admin.bmaas@nutanix.com",
    "tenant-fname": "admin",
    "tenant-lname": "bmaas",
    "tenant-role": "bmaas-admin",
    "is_provider_admin": true,
    "provider_prefix": "bmaas",
    "authorization": "Bearer bmaas_kool"
  },
  "level": "audit",
  "timestamp": "2021-05-11T23:19:11.277Z"
}

### Steps to Reproduce

1. Defined a provider X
2. Defined a procedure Y,
3. Provided input of spec to the procedure
`{"input": {"x": 10, "y": 20}}`

### Impact

This bug causes the machine entity to get stuck and provisioning will fail for the node.

### Additional Details

Logs: https://app.circleci.com/pipelines/github/nutanix/bmaas/1072/workflows/1b7bec70-cd98-4988-8e3e-7ab51c455513/jobs/1129

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by nitesh-idnani1** [comment]
After my discussion with @joshua-berry-ntnx, we feel this issue is caused by a race condition in the watchlist update operation. Fixing the race using a hash based approach to find conflict and retry the update op in case of watchlist conflicts.
